export const SET_PRODUCTS = "PRODUCTS/DATA";
export const SET_PRODUCTS_ERROR = "PRODUCTS/ERROR";
export const SET_PRODUCTS_LOADING = "PRODUCTS/LOADING";
export const SET_PRODUCTS_SELECTED = "PRODUCTS/SELECTED";

export const SET_ORDERS = "ORDERS/DATA";
export const SET_ORDERS_ERROR = "ORDERS/ERROR";
export const SET_ORDERS_LOADING = "ORDERS/LOADING";
export const SET_ORDERS_SELECTED = "ORDERS/SELECTED";

export const SET_CARTS = "CARTS/DATA";
export const SET_CARTS_ERROR = "CARTS/ERROR";
export const SET_CARTS_LOADING = "CARTS/LOADING";
export const SET_CARTS_SELECTED = "CARTS/SELECTED";