export const SET_PRODUCTS = "PRODUCTS/DATA";
export const SET_PRODUCTS_ERROR = "PRODUCTS/ERROR";
export const SET_PRODUCTS_LOADING = "PRODUCTS/LOADING";
export const SET_PRODUCTS_SELECTED = "PRODUCTS/SELECTED";
